// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  Ask a regulated question. Fail-closed: any error becomes an `Outcome::Abstain` — never an
	 *  `Err` to the UI, never a panic. Emits a progress string per stage via `on_progress`.
	 * 
	 *  Concurrency: the store lock is taken ONLY inside the two synchronous closures
	 *  (`retrieve`, `record`), each of which locks → does its blocking rusqlite work → drops the
	 *  guard at the end of the closure. No `MutexGuard` is ever held across an `.await`; the
	 *  async route/extract/solve work in between holds no lock.
	 */
	ask: (question: string, asOfDate: string | null, onProgress: Channel<string>) => typedError<Outcome, EngineError>(__TAURI_INVOKE("ask", { question, asOfDate, onProgress })),
	/**
	 *  Submit an expert correction (uses the `LiveScorer` for the verification gate). A
	 *  `fact_mapping` lesson is distilled → gated → stored provisional; a rule/vocabulary
	 *  correction is queued for a human. The store lock is held only for this synchronous call;
	 *  the LiveScorer builds its own runtime internally and holds no store lock.
	 */
	submitCorrection: (input: CorrectionInput) => typedError<SubmitResult_Serialize, EngineError>(__TAURI_INVOKE("submit_correction", { input })),
	/**  Human approval (provisional → trusted). Refused unless the verification gate passed. */
	approve: (id: string, approver: string) => typedError<StoredStrategyItem_Serialize, EngineError>(__TAURI_INVOKE("approve", { id, approver })),
	/**  Every registered accounting topic (loaded from the bundled rules modules). */
	listTopics: () => __TAURI_INVOKE<Topic[]>("list_topics"),
	/**  The most recent `n` episodes (the raw material corrections attach to). */
	recentEpisodes: (n: number) => __TAURI_INVOKE<Episode[]>("recent_episodes", { n }),
	/**
	 *  Strategy items, optionally filtered by trust state ("provisional" | "trusted"). An
	 *  unrecognized filter string yields an empty list (fail-closed).
	 */
	listStrategyItems: (trustState: string | null) => __TAURI_INVOKE<StoredStrategyItem_Serialize[]>("list_strategy_items", { trustState }),
};

/* Types */
/**  An expert correction attached to an episode. */
export type Correction = {
	id: string,
	created_at: string,
	episode_id: string,
	type: CorrectionType,
	corrected_decision: string | null,
	/**  The § the expert cites (required for a `fact_mapping` to pass citation-exists). */
	governing_section: string | null,
	expert: string,
	note: string | null,
};

/**  Fields of a `Correction` minus the store-assigned `id` and `created_at`. */
export type CorrectionInput = {
	episode_id: string,
	type: CorrectionType,
	corrected_decision: string | null,
	governing_section: string | null,
	expert: string,
	note: string | null,
};

/**
 *  The correction type decides what gets learned (ADR-0007): only `FactMapping` becomes a
 *  strategy item; `RuleDefect`/`VocabularyGap` edit the symbolic moat and route to a human.
 */
export type CorrectionType = "fact_mapping" | "rule_defect" | "vocabulary_gap";

/**  Engine error. Every fallible boundary maps to one of these or to an abstain. */
export type EngineError = 
/**  A topic-module manifest or rules file could not be read or parsed. */
({ Topics: string }) & { Budget?: never; Claude?: never; Learn?: never; Store?: never } | 
/**  The LLM driver failed (spawn, timeout, non-zero exit, bad JSON, is_error). */
({ Claude: string }) & { Budget?: never; Learn?: never; Store?: never; Topics?: never } | 
/**  A budget ceiling (call count or USD spend) was exceeded. */
({ Budget: string }) & { Claude?: never; Learn?: never; Store?: never; Topics?: never } | 
/**
 *  A datastore operation failed (rusqlite error, bad enum, missing row) or could not
 *  be serialized/deserialized.
 */
({ Store: string }) & { Budget?: never; Claude?: never; Learn?: never; Topics?: never } | 
/**  A learning-loop precondition failed (orphan episode, missing governing §, etc.). */
({ Learn: string }) & { Budget?: never; Claude?: never; Store?: never; Topics?: never };

/**  Every solve, persisted as the raw material a correction attaches to. */
export type Episode = {
	id: string,
	created_at: string,
	topic: string | null,
	question: string,
	as_of_date: string,
	facts: string[] | null,
	decision: string | null,
	status: string,
	citations: string[],
};

/**
 *  The verification-gate verdict. Approval is refused unless `passed` is true — a poisoned
 *  lesson cannot be promoted even by a human.
 */
export type GateResult = {
	passed: boolean,
	/**  Why it failed (empty when passed). */
	reasons: string[],
	baseline_accuracy: number | null,
	candidate_accuracy: number | null,
};

/**  The regulated answer, or a refusal. The single thing the gate produces. */
export type Outcome = { kind: "answer"; decision: string; citations: string[]; justification: string[] } | { kind: "abstain"; reason: string };

/**
 *  Where a strategy item came from. An item with no `episode_id`/`correction_id` is an
 *  orphan (self-generated, unattributable) and the verification gate blocks it.
 */
export type Provenance = Provenance_Serialize | Provenance_Deserialize;

/**
 *  Where a strategy item came from. An item with no `episode_id`/`correction_id` is an
 *  orphan (self-generated, unattributable) and the verification gate blocks it.
 */
export type Provenance_Deserialize = {
	episode_id: string | null,
	correction_id: string | null,
	source: string,
};

/**
 *  Where a strategy item came from. An item with no `episode_id`/`correction_id` is an
 *  orphan (self-generated, unattributable) and the verification gate blocks it.
 */
export type Provenance_Serialize = {
	episode_id?: string | null,
	correction_id?: string | null,
	source: string,
};

/**
 *  One slot in a topic's FIXED vocabulary. Lives in `manifest.json` (data, not code),
 *  so a new accounting area is a drop-in module — never an engine edit.
 */
export type SlotSpec = {
	/**  Allowed values (excludes "unknown"). */
	enum: string[],
	/**  ASP fact with "{}" replaced by the value, e.g. "vat_status(supplier, {})". */
	factTemplate: string,
};

/**
 *  A `StrategyItem` enriched with store/learning metadata: identity, staged trust,
 *  provenance, delta counters, the gate verdict, and the human approval stamp.
 */
export type StoredStrategyItem = StoredStrategyItem_Serialize | StoredStrategyItem_Deserialize;

/**
 *  A `StrategyItem` enriched with store/learning metadata: identity, staged trust,
 *  provenance, delta counters, the gate verdict, and the human approval stamp.
 */
export type StoredStrategyItem_Deserialize = {
	id: string,
	created_at: string,
	title: string,
	description: string,
	content: string,
	tags: string[],
	trust_state: TrustState,
	provenance: Provenance_Deserialize,
	helpful: number,
	harmful: number,
	gate: GateResult | null,
	approved_by: string | null,
	approved_at: string | null,
};

/**
 *  A `StrategyItem` enriched with store/learning metadata: identity, staged trust,
 *  provenance, delta counters, the gate verdict, and the human approval stamp.
 */
export type StoredStrategyItem_Serialize = {
	id: string,
	created_at: string,
	title: string,
	description: string,
	content: string,
	tags: string[],
	trust_state: TrustState,
	provenance: Provenance_Serialize,
	helpful: number,
	harmful: number,
	gate?: GateResult | null,
	approved_by?: string | null,
	approved_at?: string | null,
};

/**
 *  The IPC-friendly result of submitting a correction (the `SubmitOutcome` from learn.rs is
 *  not Serialize; this is its wire shape). `routed` is "gate" (a fact_mapping lesson went
 *  through the verification gate) or "human" (a rule/vocabulary correction was queued).
 */
export type SubmitResult = SubmitResult_Serialize | SubmitResult_Deserialize;

/**
 *  The IPC-friendly result of submitting a correction (the `SubmitOutcome` from learn.rs is
 *  not Serialize; this is its wire shape). `routed` is "gate" (a fact_mapping lesson went
 *  through the verification gate) or "human" (a rule/vocabulary correction was queued).
 */
export type SubmitResult_Deserialize = {
	routed: string,
	correction: Correction,
	item: StoredStrategyItem_Deserialize | null,
};

/**
 *  The IPC-friendly result of submitting a correction (the `SubmitOutcome` from learn.rs is
 *  not Serialize; this is its wire shape). `routed` is "gate" (a fact_mapping lesson went
 *  through the verification gate) or "human" (a rule/vocabulary correction was queued).
 */
export type SubmitResult_Serialize = {
	routed: string,
	correction: Correction,
	item: StoredStrategyItem_Serialize | null,
};

/**  A single accounting topic (e.g. DPH reverse-charge), loaded from a rules module. */
export type Topic = {
	/**  Module id, e.g. "dph-reverse-charge". */
	id: string,
	/**  rule_version.ruleset key, e.g. "dph_reverse_charge". */
	ruleset: string,
	/**  One line, used by the router. */
	description: string,
	/**  Extraction system prompt (reason-then-emit). */
	systemPrompt: string,
	slots: { [key in string]: SlotSpec },
	tags: string[],
	/**  Absolute path to rules.lp (resolved at load time; not part of the manifest). */
	rulesPath?: string,
};

/**
 *  Staged trust. v1 has exactly two states (ADR-0006): a freshly distilled lesson is
 *  `Provisional` and only a human approval (refused unless the gate passed) makes it
 *  `Trusted` and therefore retrievable.
 */
export type TrustState = "provisional" | "trusted";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

